var texturesSources = {
  vide:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        HG:false,
        H:false,
        HD:false,
        G:false,
        N:true,
        D:false,
        BG:false,
        B:false,
        BD:false
      }
    ]
  },
  pilier:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        HG:false,
        H:true,
        HD:false,
        G:false,
        N:true,
        D:false,
        BG:false,
        B:true,
        BD:false
      }
    ]
  },
  maisonMur:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        HG:false,
        H:false,
        HD:false,
        G:false,
        N:false,
        D:false,
        BG:true,
        B:true,
        BD:true
      },
      {
        HG:false,
        H:true,
        HD:false,
        G:false,
        N:true,
        D:false,
        BG:false,
        B:true,
        BD:false
      }
    ]
  },
  maisonPorte:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        HG:false,
        H:true,
        HD:false,
        G:false,
        N:false,
        D:false,
        BG:false,
        B:true,
        BD:false
      }
    ]
  },
  escalier:{
    type:"decors",
    franchissable:true,
    orientationsImage:[
      {
        HG:false,
        H:true,
        HD:false,
        G:true,
        N:false,
        D:true,
        BG:false,
        B:true,
        BD:false
      }
    ]
  },
  fenetre:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        HG:false,
        H:false,
        HD:false,
        G:false,
        N:true,
        D:false,
        BG:false,
        B:false,
        BD:false
      }
    ]
  },
  sol:{
    type:"decors",
    franchissable:true,
    orientationsImage:[
      {
        HG:false,
        H:false,
        HD:false,
        G:false,
        N:true,
        D:false,
        BG:false,
        B:false,
        BD:false
      }
    ]
  },
  personnage:{
    type:"personnage",
    franchissable:false,
    orientationsImage:[
      {
        HG:false,
        H:true,
        HD:false,
        G:true,
        N:false,
        D:true,
        BG:false,
        B:true,
        BD:false
      }
    ]
  },
  coeur:{
    type:"vivants",
    franchissable:true,
    orientationsImage:[
      {
        demi:true,
        plein:true,
        vide:true
      }
    ]
  },
  boss:{
    type:"monstre",
    orientationsImage:[
      {
        HG:false,
        H:false,
        HD:false,
        G:false,
        N:true,
        D:false,
        BG:false,
        B:false,
        BD:false
      }
    ]
  },
  boulet:{
    type:"vivants",
    orientationsImage:[
      {
        HG:false,
        H:false,
        HD:false,
        G:false,
        N:true,
        D:false,
        BG:false,
        B:false,
        BD:false
      }
    ]
  }
};
