var texturesSources = {
  arbre:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        HG:false,
        H:false,
        HD:false,
        G:false,
        N:true,
        D:false,
        BG:false,
        B:false,
        BD:false
      }
    ]
  },
  pelouse:{
    type:"decors",
    franchissable:true,
    orientationsImage:[
      {
        HG:false,
        H:false,
        HD:false,
        G:false,
        N:true,
        D:false,
        BG:false,
        B:false,
        BD:false
      }
    ]
  },
  chemin:{
    type:"decors",
    franchissable:true,
    orientationsImage:[
      {
        HG:true,
        H:true,
        HD:true,
        G:true,
        N:true,
        D:true,
        BG:false,
        B:true,
        BD:false
      },
      {
        HG:true,
        H:true,
        HD:true,
        G:true,
        N:true,
        D:true,
        BG:true,
        B:true,
        BD:true
      }
    ]
  },
  eau:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        HG:true,
        H:true,
        HD:true,
        G:true,
        N:true,
        D:true,
        BG:true,
        B:true,
        BD:true
      }
    ]
  },
  mur:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        HG:false,
        H:true,
        HD:false,
        G:true,
        N:false,
        D:true,
        BG:false,
        B:true,
        BD:false
      }
    ]
  },
  escalier:{
    type:"decors",
    franchissable:true,
    orientationsImage:[
      {
        HG:false,
        H:true,
        HD:false,
        G:true,
        N:false,
        D:true,
        BG:false,
        B:true,
        BD:false
      }
    ]
  },
  maisonMur:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        HG:false,
        H:false,
        HD:false,
        G:false,
        N:false,
        D:false,
        BG:true,
        B:true,
        BD:true
      }
    ]
  },
  maisonToit:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        HG:true,
        H:false,
        HD:true,
        G:true,
        N:true,
        D:true,
        BG:true,
        B:true,
        BD:true
      }
    ]
  },
  maisonPorte:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        HG:false,
        H:false,
        HD:false,
        G:false,
        N:true,
        D:false,
        BG:false,
        B:false,
        BD:false
      }
    ]
  },
  pnj:{
    type:"personnage",
    franchissable:false,
    orientationsImage:[
      {
        HG:false,
        H:true,
        HD:false,
        G:true,
        N:false,
        D:true,
        BG:false,
        B:true,
        BD:false
      }
    ]
  },
  personnage:{
    type:"personnage",
    franchissable:false,
    orientationsImage:[
      {
        HG:false,
        H:true,
        HD:false,
        G:true,
        N:false,
        D:true,
        BG:false,
        B:true,
        BD:false
      }
    ]
  },
  coeur:{
    type:"vivants",
    franchissable:true,
    orientationsImage:[
      {
        demi:true,
        plein:true,
        vide:true
      }
    ]
  },
  monstre:{
    type:"monstre",
    franchissable:false,
    orientationsImage:[
      {
        H:true,
        G:true,
        D:true,
        B:true
      },
      {
        H:true,
        G:true,
        D:true,
        B:true
      }
    ]
  }
};
