var texturesSources = {
  arbre:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        B:false,
        BD:false,
        BG:false,
        H:false,
        HD:false,
        HG:false,
        D:false,
        G:false,
        N:true
      }
    ]
  },
  chemin:{
    type:"decors",
    franchissable:true,
    orientationsImage:[
      {
        B:true,
        BD:false,
        BG:false,
        H:true,
        HD:true,
        HG:true,
        D:true,
        G:true,
        N:true
      },
      {
        B:true,
        BD:true,
        BG:true,
        H:true,
        HD:true,
        HG:true,
        D:true,
        G:true,
        N:true
      }
    ]
  },
  coeur:{
    type:"vivants",
    franchissable:true,
    orientationsImage:[
      {
        demi:true,
        plein:true,
        vide:true
      }
    ]
  },
  eau:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        B:true,
        BD:true,
        BG:true,
        H:true,
        HD:true,
        HG:true,
        D:true,
        G:true,
        N:true
      }
    ]
  },
  escalier:{
    type:"decors",
    franchissable:true,
    orientationsImage:[
      {
        B:true,
        BD:false,
        BG:false,
        H:true,
        HD:false,
        HG:false,
        D:true,
        G:true,
        N:false      }
    ]
  },
  fenetre:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        B:false,
        BD:false,
        BG:false,
        H:false,
        HD:false,
        HG:false,
        D:false,
        G:false,
        N:true
      }
    ]
  },
  maisonMur:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        B:true,
        BD:true,
        BG:true,
        H:false,
        HD:false,
        HG:false,
        D:false,
        G:false,
        N:false
      },
      {
        B:true,
        BD:false,
        BG:false,
        H:true,
        HD:false,
        HG:false,
        D:false,
        G:false,
        N:true
      }
    ]
  },
  maisonPorte:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        B:true,
        BD:false,
        BG:false,
        H:true,
        HD:false,
        HG:false,
        D:false,
        G:false,
        N:false
      }
    ]
  },
  maisonToit:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        B:true,
        BD:true,
        BG:true,
        H:false,
        HD:true,
        HG:true,
        D:true,
        G:true,
        N:true
      }
    ]
  },
  monstre:{
    type:"monstre",
    franchissable:false,
    orientationsImage:[
      {
        B:true,
        D:true,
        G:true,
        H:true
      },
      {
        B:true,
        D:true,
        G:true,
        H:true
      }
    ]
  },
  mur:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        B:true,
        BD:false,
        BG:false,
        H:true,
        HD:false,
        HG:false,
        D:true,
        G:true,
        N:false
      }
    ]
  },
  personnage:{
    type:"personnage",
    franchissable:false,
    orientationsImage:[
      {
        B:true,
        BD:false,
        BG:false,
        H:true,
        HD:false,
        HG:false,
        D:true,
        G:true,
        N:false
      }
    ]
  },
  pilier:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        B:true,
        BD:false,
        BG:true,
        H:true,
        HD:false,
        HG:true,
        D:false,
        G:true,
        N:true
      }
    ]
  },
  pnj:{
    type:"personnage",
    franchissable:false,
    orientationsImage:[
      {
        B:true,
        BD:false,
        BG:false,
        H:true,
        HD:false,
        HG:false,
        D:true,
        G:true,
        N:false
      }
    ]
  },
  sol:{
    type:"decors",
    franchissable:true,
    orientationsImage:[
      {
        B:false,
        BD:false,
        BG:false,
        H:false,
        HD:false,
        HG:false,
        D:false,
        G:false,
        N:true
      },
      {
        B:false,
        BD:false,
        BG:false,
        H:false,
        HD:false,
        HG:false,
        D:false,
        G:false,
        N:true
      },
      {
        B:false,
        BD:false,
        BG:false,
        H:false,
        HD:false,
        HG:false,
        D:false,
        G:false,
        N:true
      },
      {
        B:false,
        BD:false,
        BG:false,
        H:false,
        HD:false,
        HG:false,
        D:false,
        G:false,
        N:true
      }
    ]
  },
  vide:{
    type:"decors",
    franchissable:false,
    orientationsImage:[
      {
        B:false,
        BD:false,
        BG:false,
        H:false,
        HD:false,
        HG:false,
        D:false,
        G:false,
        N:true
      }
    ]
  }
};
